### ISSUE TITLE
vulkan issues preventing launch

### ISSUE THREAD

**Issue by wlvc** [katalash/DSMapStudio#16]
I get this error in the EventViewer when I try to launch (it crashes immediately -- I have all the Win components installed like Visual C++ and .NET):

```
Application: DSMapStudio.exe
CoreCLR Version: 4.700.20.56602
.NET Core Version: 3.1.11
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Veldrid.Vk.VkSwapchain.CreateSwapchain(UInt32 width, UInt32 height) in E:\soulsmodsstuff\soulsmodsgh\og\DSMapStudio\Veldrid\Vk\VkSwapchain.cs:line 138
   at Veldrid.Vk.VkSwapchain..ctor(VkGraphicsDevice gd, SwapchainDescription& description, VkSurfaceKHR existingSurface) in E:\soulsmodsstuff\soulsmodsgh\og\DSMapStudio\Veldrid\Vk\VkSwapchain.cs:line 76
   at Veldrid.Vk.VkGraphicsDevice..ctor(GraphicsDeviceOptions options, Nullable1 scDesc, VulkanDeviceOptions vkOptions) in E:\soulsmodsstuff\soulsmodsgh\og\DSMapStudio\Veldrid\Vk\VkGraphicsDevice.cs:line 159
   at Veldrid.GraphicsDevice.CreateVulkan(GraphicsDeviceOptions options, SwapchainDescription swapchainDescription, VulkanDeviceOptions vkOptions) in E:\soulsmodsstuff\soulsmodsgh\og\DSMapStudio\Veldrid\GraphicsDevice.cs:line 989
   at Veldrid.StartupUtilities.VeldridStartup.CreateVulkanGraphicsDevice(GraphicsDeviceOptions options, Sdl2Window window, Boolean colorSrgb) in E:\soulsmodsstuff\soulsmodsgh\og\DSMapStudio\Veldrid.StartupUtilities\VeldridStartup.cs:line 225
   at Veldrid.StartupUtilities.VeldridStartup.CreateVulkanGraphicsDevice(GraphicsDeviceOptions options, Sdl2Window window) in E:\soulsmodsstuff\soulsmodsgh\og\DSMapStudio\Veldrid.StartupUtilities\VeldridStartup.cs:line 209
   at Veldrid.StartupUtilities.VeldridStartup.CreateGraphicsDevice(Sdl2Window window, GraphicsDeviceOptions options, GraphicsBackend preferredBackend) in E:\soulsmodsstuff\soulsmodsgh\og\DSMapStudio\Veldrid.StartupUtilities\VeldridStartup.cs:line 112
   at Veldrid.StartupUtilities.VeldridStartup.CreateWindowAndGraphicsDevice(WindowCreateInfo windowCI, GraphicsDeviceOptions deviceOptions, GraphicsBackend preferredBackend, Sdl2Window& window, GraphicsDevice& gd) in E:\soulsmodsstuff\soulsmodsgh\og\DSMapStudio\Veldrid.StartupUtilities\VeldridStartup.cs:line 44
   at StudioCore.MapStudioNew..ctor() in E:\soulsmodsstuff\soulsmodsgh\og\DSMapStudio\StudioCore\MapStudioNew.cs:line 105
   at DSMapStudio.Program.Main(String[] args)
```

I have reinstalled my graphics driver (both Studio and Game Ready, manually and automatically from Nvidia), reinstalled the Vulkan SDK and runtime, etc.  I am using an Nvidia Geforce 1070

Something interesting in the output above is the filepaths are not mine -- I suspect they are the dev's. E.g.:  `E:\soulsmodsstuff\soulsmodsgh\og\DSMapStudio\Veldrid.StartupUtilities\VeldridStartup.cs:line 44`

I am trying to run the DSMapStudio.exe from the 7z file provided

Any thoughts on debugging?

**Comment by amineyarman** [comment]
Try this. Check my last comment.
https://github.com/katalash/DSMapStudio/issues/26
