### ISSUE TITLE
crashing while trying to merge regulation bins ( elden ring 1.08.1) new to modding so not sure how to fix 

### ISSUE THREAD

**Issue by Tomrobbo1309** [katalash/DSMapStudio#38]
DSMapStudio Version 1.06
One or more errors occurred. (Could not find param file. Functionality will be limited.)

----------------------

Could not find param file. Functionality will be limited.
   at StudioCore.ParamEditor.ParamBank.LoadParamsER(Boolean partial) in D:\a\DSMapStudio\DSMapStudio\StudioCore\ParamEditor\ParamBank.cs:line 627
   at StudioCore.ParamEditor.ParamBank.<>c__DisplayClass59_0.<ReloadParams>b__0() in D:\a\DSMapStudio\DSMapStudio\StudioCore\ParamEditor\ParamBank.cs:line 732
   at StudioCore.Editor.TaskManager.<>c__DisplayClass4_0.<AddTask>b__0() in D:\a\DSMapStudio\DSMapStudio\StudioCore\Editor\TaskManager.cs:line 56
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)

**Comment by Titimaina** [comment]
I had the same problem. So i fixed it by verifying the game files from steam
